#!/bin/bash

echo "🧹 Starting Docusaurus cleanup..."

# 1. Delete the nested 'docs' folder if it exists
if [ -d "docs" ]; then
  echo "🗑 Removing extra nested 'docs/' folder..."
  rm -rf docs
  git rm -r --cached docs 2>/dev/null
fi

# 2. Fix docusaurus.config.ts
if [ -f "docusaurus.config.ts" ]; then
  echo "🛠 Updating docusaurus.config.ts to use root as docs path..."
  sed -i.bak -E "s/path: ['\"]docs['\"]?/path: '.'/" docusaurus.config.ts
  sed -i.bak -E "s/routeBasePath: ['\"]docs['\"]?/routeBasePath: '/'/" docusaurus.config.ts
  rm docusaurus.config.ts.bak
else
  echo "⚠️ docusaurus.config.ts not found!"
fi

# 3. Fix sidebars.ts
if [ -f "sidebars.ts" ]; then
  echo "🛠 Replacing sidebars.ts with autogenerated config..."
  echo "export default { tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }] };" > sidebars.ts
else
  echo "⚠️ sidebars.ts not found!"
fi

# 4. Stage and commit
echo "✅ Staging cleanup changes..."
git add .
git commit -m "Cleanup: removed duplicate docs folder, updated config and sidebar"

echo "🎉 Done! Now push in VS Code or run: git push"
