#!/bin/bash

echo "🔍 Checking for nested 'docs/docs' structure..."

if [ -d "docs/docs" ]; then
  echo "📂 Found 'docs/docs'. Flattening structure..."

  # Move files up one level
  mv docs/docs/* docs/

  # Remove old nested folder
  rm -r docs/docs

  echo "✅ Flattened 'docs/docs' to 'docs/'"
else
  echo "✅ No nested 'docs/docs' structure found"
fi

# Check and fix sidebars.js
SIDEBAR_FILE="sidebars.js"
AUTOGEN_LINE="[{ type: 'autogenerated', dirName: '.' }]"

if [ -f "$SIDEBAR_FILE" ]; then
  grep -q "$AUTOGEN_LINE" "$SIDEBAR_FILE"
  if [ $? -ne 0 ]; then
    echo "⚠️  Updating sidebar to use autogenerated mode..."
    echo "module.exports = { tutorialSidebar: $AUTOGEN_LINE };" > "$SIDEBAR_FILE"
    echo "✅ Updated sidebar to use autogenerated directory"
  else
    echo "✅ Sidebar already uses autogenerated directory"
  fi
else
  echo "🚫 'sidebars.js' not found — skipping sidebar fix"
fi

# Check for intro.md
if [ -f "docs/intro.md" ]; then
  echo "✅ 'docs/intro.md' exists — good to go!"
else
  echo "⚠️  'docs/intro.md' is missing. Consider creating a landing doc there."
fi

echo "🧼 Cleanup complete!"

#!/bin/bash

echo "🔍 Checking for nested 'docs/docs' structure..."

if [ -d "docs/docs" ]; then
  echo "📂 Found 'docs/docs'. Flattening structure..."

  # Move files up one level
  mv docs/docs/* docs/

  # Remove old nested folder
  rm -r docs/docs

  echo "✅ Flattened 'docs/docs' to 'docs/'"
else
  echo "✅ No nested 'docs/docs' structure found"
fi

# Check and fix sidebars.js
SIDEBAR_FILE="sidebars.js"
AUTOGEN_LINE="[{ type: 'autogenerated', dirName: '.' }]"

if [ -f "$SIDEBAR_FILE" ]; then
  grep -q "$AUTOGEN_LINE" "$SIDEBAR_FILE"
  if [ $? -ne 0 ]; then
    echo "⚠️  Updating sidebar to use autogenerated mode..."
    echo "module.exports = { tutorialSidebar: $AUTOGEN_LINE };" > "$SIDEBAR_FILE"
    echo "✅ Updated sidebar to use autogenerated directory"
  else
    echo "✅ Sidebar already uses autogenerated directory"
  fi
else
  echo "🚫 'sidebars.js' not found — skipping sidebar fix"
fi

# Check for intro.md
if [ -f "docs/intro.md" ]; then
  echo "✅ 'docs/intro.md' exists — good to go!"
else
  echo "⚠️  'docs/intro.md' is missing. Consider creating a landing doc there."
fi

echo "🧼 Cleanup complete!"

#!/bin/bash

echo "🔍 Checking for nested 'docs/docs' structure..."

if [ -d "docs/docs" ]; then
  echo "📂 Found 'docs/docs'. Flattening structure..."

  # Move files up one level
  mv docs/docs/* docs/

  # Remove old nested folder
  rm -r docs/docs

  echo "✅ Flattened 'docs/docs' to 'docs/'"
else
  echo "✅ No nested 'docs/docs' structure found"
fi

# Check and fix sidebars.js
SIDEBAR_FILE="sidebars.js"
AUTOGEN_LINE="[{ type: 'autogenerated', dirName: '.' }]"

if [ -f "$SIDEBAR_FILE" ]; then
  grep -q "$AUTOGEN_LINE" "$SIDEBAR_FILE"
  if [ $? -ne 0 ]; then
    echo "⚠️  Updating sidebar to use autogenerated mode..."
    echo "module.exports = { tutorialSidebar: $AUTOGEN_LINE };" > "$SIDEBAR_FILE"
    echo "✅ Updated sidebar to use autogenerated directory"
  else
    echo "✅ Sidebar already uses autogenerated directory"
  fi
else
  echo "🚫 'sidebars.js' not found — skipping sidebar fix"
fi

# Check for intro.md
if [ -f "docs/intro.md" ]; then
  echo "✅ 'docs/intro.md' exists — good to go!"
else
  echo "⚠️  'docs/intro.md' is missing. Consider creating a landing doc there."
fi

echo "🧼 Cleanup complete!"
