site_name: Paisley Documentation
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  
  - Tokenomics:
    - $CVM Purchase: Buy-Convex/index.md
    